docker:
  image: yegor256/rultor-ruby
assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |-
  sudo gem install pdd
  pdd -f /dev/null
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
release:
  script: |-
    bundle exec rake
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" tacky.gemspec
    git add tacky.gemspec
    git commit -m "Version set to ${tag}"
    gem build tacky.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle install
    bundle exec rake
